version: '3.8'

services:
  production:
    build:
      context: ./
      dockerfile: test-servers/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ENV_NAME=production
      - PORT=8080
    restart: always

  staging:
    build:
      context: ./
      dockerfile: test-servers/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ENV_NAME=staging
      - PORT=8080
    restart: always

  baseline:
    build:
      context: ./
      dockerfile: test-servers/Dockerfile
    ports:
      - "8083:8080"
    environment:
      - ENV_NAME=baseline
      - PORT=8080
    restart: always
