// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RecomputeDiff(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RecomputeDiff'](arg1, arg2, arg3, arg4);
}

export function SendDiffRequest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendDiffRequest'](arg1, arg2, arg3, arg4, arg5);
}

export function SendRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2, arg3);
}
