// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function RecomputeDiff(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<model.DiffResponse>;

export function SendDiffRequest(arg1:string,arg2:string,arg3:string,arg4:model.Targets,arg5:Array<string>):Promise<model.DiffResponse>;

export function SendRequest(arg1:string,arg2:string,arg3:string):Promise<model.Response>;
