// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProtoMessageFields(arg1, arg2) {
  return window['go']['main']['App']['GetProtoMessageFields'](arg1, arg2);
}

export function GetProtoMessageTemplate(arg1, arg2) {
  return window['go']['main']['App']['GetProtoMessageTemplate'](arg1, arg2);
}

export function GetProtoMessages(arg1) {
  return window['go']['main']['App']['GetProtoMessages'](arg1);
}

export function GetProtoSchemaFields(arg1) {
  return window['go']['main']['App']['GetProtoSchemaFields'](arg1);
}

export function RecomputeDiff(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RecomputeDiff'](arg1, arg2, arg3, arg4);
}

export function SendDiffRequest(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SendDiffRequest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SendRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2, arg3);
}
