// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {model} from '../models';

export function GetProtoMessageFields(arg1:string,arg2:string):Promise<Array<service.ProtoField>>;

export function GetProtoMessageTemplate(arg1:string,arg2:string):Promise<string>;

export function GetProtoMessages(arg1:string):Promise<Array<string>>;

export function GetProtoSchemaFields(arg1:string):Promise<Record<string, Array<service.ProtoField>>>;

export function RecomputeDiff(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<model.DiffResponse>;

export function SendDiffRequest(arg1:string,arg2:string,arg3:string,arg4:model.Targets,arg5:Array<string>,arg6:string,arg7:string,arg8:string):Promise<model.DiffResponse>;

export function SendRequest(arg1:string,arg2:string,arg3:string):Promise<model.Response>;
